# Site settings
title: 租客联盟信息汇总站
copyright: 租客联盟成员&copy;李棉酷
email: 2468496@qq.com
description: > # this means to ignore newlines until "baseurl:"
  租客联盟信息汇总站
baseurl: # the subpath of your site, e.g. /blog/
url: "http://zukelm.com" # the base hostname & protocol for your site
twitter_username: 李棉酷
github_username:  李棉酷

# Build settings
markdown: kramdown
host:
